// Chinese strings for `tr()`. Keys are the English text exactly as written in code.
extension L10n {
    static let chinese: [String: String] = [
        "From Sidebar": "来自侧栏",
        "Remove this filter": "移除此筛选",
        "  ·  not upscaled": "  ·  不放大",
        " %@ Photos": " %@ 张照片",
        " %@ could not be decoded and were skipped.": " %@ 张无法解码，已跳过。",
        "%@ %@ long edge": "长边 %@ %@",
        "%@ all selected (%@)": "全部标为%@（%@）",
        "%@ photos": "%@ 张照片",
        "%@ photos in this collection are missing on disk": "此收藏中有 %@ 张照片在磁盘上找不到",
        "%@ preview unavailable": "%@ 无法预览",
        "%@ selected": "已选 %@ 张",
        "%@ shown": "显示 %@ 张",
        "%@ stars": "%@ 星",
        "%@ — %@ filters active": "%@ — %@ 个筛选条件生效中",
        "%@ — 1 filter active": "%@ — 1 个筛选条件生效中",
        "18% gray canvas for color-critical culling": "18% 中灰画布，适合校色挑片",
        "Actual Pixels (1:1)": "实际像素 (1:1)",
        "Actual pixels (100%)": "实际像素 (100%)",
        "Add Selected Photos": "添加所选照片",
        "Add or remove groups by hand": "手动添加或移除分组",
        "Add to / extend selection": "加选 / 连续选择",
        "Add to / remove from target collection": "加入 / 移出目标收藏",
        "Add to Collection": "添加到收藏",
        "Add to Target Collection (B)": "添加到目标收藏 (B)",
        "Added %@ to “%@”": "已将 %@ 张添加到“%@”",
        "Adobe Light Gray": "Adobe 浅灰",
        "Adobe Style": "Adobe 风格",
        "After Pick or Reject, go to the next photo": "标记留用或排除后，自动跳到下一张",
        "All": "全部",
        "All Photos": "所有照片",
        "Already in “%@”": "已在“%@”中",
        "Analyze Automatically": "自动分析",
        "Analyzing %@ / %@": "正在分析 %@ / %@",
        "Analyzing…": "正在分析…",
        "Any": "不限",
        "Aperture": "光圈",
        "App": "应用",
        "Applies to chrome, panels, and the image canvas. Original photos are unchanged.": "作用于窗口、面板和画布，原始照片不会改变。",
        "Apply, then go to next photo": "标记后跳到下一张",
        "Auto Groups": "智能分组",
        "Back to Folder": "返回文件夹",
        "Back to folder": "返回文件夹",
        "Back to this folder": "返回此文件夹",
        "Black & white": "黑白",
        "Blue": "蓝色",
        "Body": "机身",
        "Brand": "品牌",
        "Bridge / Photoshop light theme": "Bridge / Photoshop 浅色主题",
        "Camera": "相机",
        "Cancel": "取消",
        "Capture Date": "拍摄日期",
        "Centimeters (cm)": "厘米 (cm)",
        "Charcoal panels, silver highlights": "炭灰面板，银灰高亮",
        "Choose a photo folder to browse. Original files are never modified.": "选择一个照片文件夹开始浏览，原始文件永远不会被修改。",
        "Classic Solarized dark": "经典 Solarized 深色",
        "Clear": "清除",
        "Clear Filters": "清除筛选",
        "Clear Rating (0)": "清除星级 (0)",
        "Clear rating (0)": "清除星级 (0)",
        "Clear selection (Esc)": "取消选择 (Esc)",
        "Collections": "收藏",
        "Collections & Groups": "收藏与分组",
        "Collections only reference photos; files are not copied or moved.": "收藏只引用照片，不会复制或移动文件。",
        "Color": "颜色",
        "Color Label": "颜色标签",
        "Color Labels": "颜色标签",
        "Color space": "色彩空间",
        "Combine auto groups or places": "组合多个分组或地点",
        "Common sizes": "常用尺寸",
        "Content": "内容",
        "Content Groups": "内容分组",
        "Content analysis is unavailable on this Mac right now (Vision could not process images). Photos were left unchanged; try again later from Library ▸ Group Photos by Content.": "这台 Mac 暂时无法进行内容分析（Vision 无法处理图像）。照片未作任何改动，请稍后通过“图库 ▸ 按内容分组”重试。",
        "Cool dark culling desk": "偏冷的暗色挑片台",
        "Copied %@ paths": "已复制 %@ 个路径",
        "Copied %@ photos": "已复制 %@ 张照片",
        "Copied %@ photos to %@.": "已将 %@ 张照片复制到 %@。",
        "Copied 1 photo": "已复制 1 张照片",
        "Copied image": "已复制图像",
        "Copied path": "已复制路径",
        "Copy": "拷贝",
        "Copy %@ original files. Existing files are never overwritten.": "复制 %@ 个原始文件，不会覆盖已有文件。",
        "Copy Files (⌘C)": "拷贝文件 (⌘C)",
        "Copy Here": "复制到这里",
        "Copy Image": "拷贝图像",
        "Copy Path": "拷贝路径",
        "Copy Paths": "拷贝路径",
        "Copy Selected Files (⌘C)": "拷贝所选文件 (⌘C)",
        "Copy Selected to Folder…": "将所选复制到文件夹…",
        "Copy failed: %@": "复制失败：%@",
        "Copy files": "拷贝文件",
        "Copy original files (never modified)": "复制原始文件（不作修改）",
        "Copy to Folder…": "复制到文件夹…",
        "Copy%@  ⌘C": "拷贝%@  ⌘C",
        "Could not prepare photos for Mail.": "无法为邮件准备照片。",
        "Could not set desktop picture: %@": "无法设为桌面图片：%@",
        "Created “%@”": "已创建“%@”",
        "Dark": "暗色",
        "Dark gray UI, Photoshop blue": "深灰界面，Photoshop 蓝",
        "Daylight": "日光",
        "Decrease / increase rating": "降低 / 提高星级",
        "Decrease Rating ([)": "降低星级 ([)",
        "Delete": "删除",
        "Delete Collection…": "删除收藏…",
        "Delete “%@”?": "删除“%@”？",
        "Desktop picture set": "已设为桌面图片",
        "Detect people, sports, pets, nature… on this Mac. Nothing is uploaded.": "在本机识别人物、运动、宠物、自然风光等，不上传任何内容。",
        "Done": "完成",
        "Drop photos onto a collection": "把照片拖到收藏上",
        "Edit in Preview": "在“预览”中编辑",
        "Edit…": "编辑…",
        "Email": "邮件",
        "Enter a value greater than 0.": "请输入大于 0 的数值。",
        "Estimated output": "预计输出",
        "Estimating…": "正在估算…",
        "Expand %@": "展开%@",
        "Export": "导出",
        "Export %@ photos": "导出 %@ 张照片",
        "Export %@ photos. Originals stay untouched.": "导出 %@ 张照片，原始文件保持不变。",
        "Export Picked Photos…": "导出留用照片…",
        "Export Selected…": "导出所选…",
        "Export Selected… (⇧⌘E)": "导出所选… (⇧⌘E)",
        "Export Visible Photos…": "导出当前显示的照片…",
        "Export failed: %@": "导出失败：%@",
        "Export%@…  ⇧⌘E": "导出%@…  ⇧⌘E",
        "Exported %@ photos to %@.": "已将 %@ 张照片导出到 %@。",
        "Exporting…": "正在导出…",
        "Export…": "导出…",
        "Exposure": "曝光",
        "File": "文件",
        "File Type": "文件类型",
        "Filename": "文件名",
        "Files": "文件",
        "Filmstrip": "胶片栏",
        "Filmstrip  F6": "胶片栏  F6",
        "Filmstrip (F6)": "胶片栏 (F6)",
        "Filter": "筛选",
        "Filter (\\ or ⌘F)  ·  Info (I)": "筛选 (\\ 或 ⌘F)  ·  信息 (I)",
        "Filter Panel": "筛选面板",
        "Filter panel": "筛选面板",
        "Find camera or lens": "查找相机或镜头",
        "First / last photo": "第一张 / 最后一张",
        "First Photo (Home)": "第一张 (Home)",
        "First photo: %@ × %@ px": "第一张：%@ × %@ 像素",
        "Fit": "适合窗口",
        "Focal Length": "焦距",
        "Folders": "文件夹",
        "Follow System": "跟随系统",
        "Forest": "松林",
        "Format": "格式",
        "Format:": "格式：",
        "Fresh blue-green light": "清爽蓝绿浅色",
        "Full-Screen Preview  F": "全屏预览  F",
        "Full-Screen Preview (F)": "全屏预览 (F)",
        "Full-screen preview (Esc to exit)": "全屏预览（Esc 退出）",
        "Graphite": "石墨",
        "Graphite gray with amber": "石墨灰配琥珀色",
        "Grayscale": "灰度",
        "Green": "绿色",
        "Grid": "网格",
        "Grid (G)": "网格 (G)",
        "Group Photos by Content": "按内容分组照片",
        "Group by Content": "按内容分组",
        "Group photos by content automatically": "自动按内容分组照片",
        "Hide %@": "隐藏%@",
        "Hide %@%@": "隐藏%@%@",
        "Hide Group": "取消该分组筛选",
        "Hide Inspector (F8)": "隐藏检查器 (F8)",
        "Hide Library (F7)": "隐藏图库 (F7)",
        "Hide info bar (')": "隐藏信息栏 (')",
        "Import Photos…": "导入照片…",
        "In the target collection": "已在目标收藏中",
        "Inches (in)": "英寸 (in)",
        "Include %@ selected photos": "包含已选的 %@ 张照片",
        "Include 1 selected photo": "包含已选的 1 张照片",
        "Increase Rating (])": "提高星级 (])",
        "Info": "信息",
        "Info Bar": "信息栏",
        "Info Bar  '": "信息栏  '",
        "Info Bar (')": "信息栏 (')",
        "Info bar": "信息栏",
        "Inspector": "检查器",
        "Inspector  F8": "检查器  F8",
        "Inspector Panel (F8)": "检查器面板 (F8)",
        "Inspector panel": "检查器面板",
        "Keep Current Only (Esc)": "只保留当前照片 (Esc)",
        "Keep only the current photo": "只保留当前照片",
        "Keyboard Shortcuts": "键盘快捷键",
        "Keyboard shortcuts (⌘/)": "键盘快捷键 (⌘/)",
        "Label all as %@": "全部标为%@",
        "Language": "语言",
        "Last Photo (End)": "最后一张 (End)",
        "Lens": "镜头",
        "Less": "收起",
        "Library": "图库",
        "Library  F7": "图库  F7",
        "Library Panel (F7)": "图库面板 (F7)",
        "Library panel": "图库面板",
        "Light": "浅色",
        "Light gray for daytime": "浅灰日光，适合白天",
        "Loading “%@”…": "正在载入“%@”…",
        "Location": "位置",
        "Long edge": "长边",
        "Look Up Place Names": "查询地名",
        "Look up place names for photos with GPS": "为带 GPS 的照片查询地名",
        "Looking up place name…": "正在查询地名…",
        "Loupe": "放大",
        "Loupe (E)": "放大 (E)",
        "Loupe (from grid)": "放大（从网格进入）",
        "Mail is not available.": "邮件不可用。",
        "Makes P / X culling almost mouse-free: mark, then the next frame is already up.": "用 P / X 挑片几乎不用鼠标：标记完，下一张已经就位。",
        "Marks": "标记",
        "Meanings are yours. PhotoFlow only stores the color.": "含义由你决定，PhotoFlow 只保存颜色。",
        "Menus and panels switch immediately. Items macOS adds itself (Edit, Window) follow after a relaunch.": "菜单和面板立即切换；系统自带的菜单项（编辑、窗口）在重新打开应用后切换。",
        "Midnight": "午夜",
        "Millimeters (mm)": "毫米 (mm)",
        "Modeled on Lightroom Classic and Photoshop.": "参照 Lightroom Classic 与 Photoshop。",
        "More +%@": "更多 +%@",
        "More in Settings…": "更多设置…",
        "More: Save As, Email, Copy, Export, Open With…": "更多：另存为、邮件、拷贝、导出、打开方式…",
        "More: Save As, Rename, Open With, Copy Paths…": "更多：另存为、重命名、打开方式、拷贝路径…",
        "Muted deep green": "低饱和墨绿",
        "Naming places %@ / %@": "正在命名地点 %@ / %@",
        "Navigate & Select": "浏览与选择",
        "Neutral Gray 18%": "中性灰 18%",
        "New Collection": "新建收藏",
        "New Collection…": "新建收藏…",
        "New Collection…  ⌘N": "新建收藏…  ⌘N",
        "New collection": "新建收藏",
        "New collection (⌘N)": "新建收藏 (⌘N)",
        "Next / previous skin": "下一个 / 上一个皮肤",
        "Next Photo (→)": "下一张 (→)",
        "Next Skin": "下一个皮肤",
        "Next Skin  ⌥⌘K": "下一个皮肤  ⌥⌘K",
        "Next photo (→)": "下一张 (→)",
        "No GPS in this file.": "此文件没有 GPS 信息。",
        "No Photo": "没有照片",
        "No Rating  0": "无星级  0",
        "No camera metadata": "没有相机信息",
        "No files renamed.": "没有文件被重命名。",
        "No folder open": "未打开文件夹",
        "No group": "未归入分组",
        "No lens metadata": "没有镜头信息",
        "No match": "无匹配",
        "No photo selected": "未选择照片",
        "No photos match these filters": "没有符合筛选条件的照片",
        "No target collection yet — press B to start one": "还没有目标收藏 — 按 B 创建一个",
        "Noir": "影院",
        "None": "无",
        "Nord": "北境",
        "Nordic cool blue-gray": "北欧冷蓝灰",
        "Not analyzed yet.": "尚未分析。",
        "Nothing to analyze": "没有需要分析的照片",
        "Nothing to export.": "没有可导出的照片。",
        "OK": "好",
        "Ocean": "海雾",
        "Only the collection is removed. The %@ photos stay on disk untouched.": "只删除收藏本身，其中 %@ 张照片保留在磁盘上，不受影响。",
        "Open": "打开",
        "Open Folder…": "打开文件夹…",
        "Open a folder (⌘O)": "打开文件夹 (⌘O)",
        "Open a folder to begin": "打开一个文件夹开始",
        "Open folder (Import)": "打开文件夹（导入）",
        "Open in Maps": "在“地图”中打开",
        "Open in Preview": "在“预览”中打开",
        "Open with Default App": "用默认应用打开",
        "Original (%@, exact copy)": "原件（%@，原样复制）",
        "Original copy": "原件复制",
        "Original copy keeps the files byte-for-byte, so size and color settings don’t apply.": "原件复制会逐字节保留文件，尺寸和色彩设置不适用。",
        "Original files stay untouched. Ratings, colors, and picks live in PhotoFlow’s SQLite database.": "原始文件保持不变。星级、颜色和留用标记保存在 PhotoFlow 的 SQLite 数据库中。",
        "Original size": "原始尺寸",
        "Originals": "原件",
        "Originals (%@)": "原件（%@）",
        "Originals are never modified. JPEG / HEIC / PNG / TIFF write new files; RAW is developed by macOS.": "原始文件永远不会被修改。JPEG / HEIC / PNG / TIFF 会写入新文件，RAW 由 macOS 解码。",
        "Panels": "面板",
        "Paper": "宣纸",
        "Path": "路径",
        "People, sports, pets, birds, nature, food… detected with Apple Vision on this Mac. Nothing is uploaded and files are never changed; results live in PhotoFlow’s database.": "人物、运动、宠物、鸟类、自然风光、美食……由本机 Apple Vision 识别。不上传任何内容，也不修改文件；结果保存在 PhotoFlow 的数据库中。",
        "Percent (%)": "百分比 (%)",
        "Photo": "照片",
        "Photo Info (I)": "照片信息 (I)",
        "Photo info": "照片信息",
        "PhotoFlow never overwrites the original. Choose another name or folder.": "PhotoFlow 不会覆盖原始文件，请换一个名称或文件夹。",
        "Pick": "留用",
        "Pick  P": "留用  P",
        "Pick (P)": "留用 (P)",
        "Pick · Reject · Unflag": "留用 · 排除 · 取消旗标",
        "Picked": "已留用",
        "Pixels (px)": "像素 (px)",
        "Place lookup is off (Settings).": "地名查询已关闭（见设置）。",
        "Place lookup paused — offline or rate-limited. It resumes next time.": "地名查询已暂停 — 可能离线或请求过于频繁，下次会继续。",
        "Place name": "地名",
        "Places": "地点",
        "Presets": "预设",
        "Preview": "预览",
        "Previous / next (loupe)": "上一张 / 下一张（放大视图）",
        "Previous / next photo": "上一张 / 下一张",
        "Previous Photo (←)": "上一张 (←)",
        "Previous Skin": "上一个皮肤",
        "Previous photo (←)": "上一张 (←)",
        "Print": "打印",
        "Print…": "打印…",
        "Print…  ⌘P": "打印…  ⌘P",
        "Pure black cinema, photos stand out": "纯黑影院，突出照片",
        "Purple": "紫色",
        "Quality": "质量",
        "Quick Collection": "快速收藏",
        "Rate all selected (1–5)": "为所选照片评星 (1–5)",
        "Rate, Flag & Label": "评星、旗标与颜色",
        "Rating": "星级",
        "Rating ★ (1)": "星级 ★ (1)",
        "Rating ★★ (2)": "星级 ★★ (2)",
        "Rating ★★★ (3)": "星级 ★★★ (3)",
        "Rating ★★★★ (4)": "星级 ★★★★ (4)",
        "Rating ★★★★★ (5)": "星级 ★★★★★ (5)",
        "Re-analyze All (keeps manual edits)": "全部重新分析（保留手动修改）",
        "Reading %@ / %@": "正在读取 %@ / %@",
        "Red": "红色",
        "Red · Yellow · Green · Blue · Purple": "红 · 黄 · 绿 · 蓝 · 紫",
        "Redo": "重做",
        "Redo Mark (⇧⌘Z)": "重做标记 (⇧⌘Z)",
        "Reject  X": "排除  X",
        "Reject (X)": "排除 (X)",
        "Rejected": "已排除",
        "Remove Location": "移除位置",
        "Remove from Collection (⌫)": "从收藏中移除 (⌫)",
        "Remove from collection (files stay)": "从收藏中移除（文件保留）",
        "Remove from “%@”  ⌫": "从“%@”中移除  ⌫",
        "Removed %@ from “%@” (files untouched)": "已从“%2$@”中移除 %1$@ 张（文件未改动）",
        "Rename": "重命名",
        "Rename %@ files": "重命名 %@ 个文件",
        "Rename Collection": "重命名收藏",
        "Rename Selected… (F2)": "重命名所选… (F2)",
        "Rename%@…": "重命名%@…",
        "Renamed %@ files.": "已重命名 %@ 个文件。",
        "Rename…": "重命名…",
        "Rename… (F2)": "重命名… (F2)",
        "Resize": "调整尺寸",
        "Resolution": "分辨率",
        "Reveal in Finder": "在访达中显示",
        "Sakura": "樱花",
        "Save": "存储",
        "Save As": "另存为",
        "Save As…": "另存为…",
        "Save As…  ⇧⌘S": "另存为…  ⇧⌘S",
        "Save as Collection": "存为收藏",
        "Save failed: %@": "存储失败：%@",
        "Save%@ As…  ⇧⌘S": "将%@另存为…  ⇧⌘S",
        "Saved %@ photos to “%@”": "已将 %@ 张照片存入“%@”",
        "Saved %@.": "已存储 %@。",
        "Scanning…": "正在扫描…",
        "Search": "搜索",
        "Search content (鸟, 狗, 海边, 风景, sunset), places (上海, Yosemite), folder or file names, camera and lens, or dates (2024-10, 2024年10月). Separate words with spaces to narrow down: “鸟 上海”.": "可搜索内容（鸟、狗、海边、风景、sunset）、地点（上海、Yosemite）、文件夹或文件名、相机和镜头，以及日期（2024-10、2024年10月）。用空格分隔多个词以缩小范围：“鸟 上海”。",
        "Search: all words must match": "搜索：所有词都需匹配",
        "Search: 鸟, 风景, 上海, 2024, Sony…": "搜索：鸟、风景、上海、2024、Sony…",
        "Select All (⌘A)": "全选 (⌘A)",
        "Select None": "取消全选",
        "Select a photo first.": "请先选择一张照片。",
        "Select a photo to inspect EXIF and marks.": "选择照片以查看 EXIF 和标记。",
        "Select all": "全选",
        "Select all visible photos (⌘A)": "选择所有显示的照片 (⌘A)",
        "Select none": "取消全选",
        "Select photos first.": "请先选择照片。",
        "Select photos in a folder and press B, use “Add to Collection” in the right-click menu, or drag photos onto the collection in the sidebar.": "在文件夹中选中照片后按 B，或使用右键菜单“添加到收藏”，也可以把照片拖到侧栏的收藏上。",
        "Selection": "选择",
        "Sends only the coordinates to Apple’s map service to get names like “上海市 · 外滩” for searching and the Places list. Photos without GPS can be tagged by hand (right-click ▸ Set Location…).": "只把坐标发送给 Apple 地图服务，获取“上海市 · 外滩”这样的地名，用于搜索和地点列表。没有 GPS 的照片可以手动标注（右键 ▸ 设置位置…）。",
        "Set Location": "设置位置",
        "Set Location for %@ Photos": "为 %@ 张照片设置位置",
        "Set Location…": "设置位置…",
        "Set as Desktop Picture": "设为桌面图片",
        "Set as Target Collection (B)": "设为目标收藏 (B)",
        "Settings": "设置",
        "Settings (⌘,)": "设置 (⌘,)",
        "Settings…": "设置…",
        "Share": "共享",
        "Share (Mail, Messages, AirDrop…)": "共享（邮件、信息、隔空投送…）",
        "Share…": "共享…",
        "Show %@": "显示%@",
        "Show Inspector — Filter (\\ or ⌘F), Info (I)": "显示检查器 — 筛选 (\\ 或 ⌘F)、信息 (I)",
        "Show Library (F7)": "显示图库 (F7)",
        "Show Only This Group": "只显示此分组",
        "Show Target Collection": "显示目标收藏",
        "Show all %@": "显示全部 %@ 个",
        "Show all %@ brands": "显示全部 %@ 个品牌",
        "Show all %@ lenses": "显示全部 %@ 个镜头",
        "Show all photos in this group": "显示此分组的所有照片",
        "Show fewer": "收起",
        "Show in Finder": "在访达中显示",
        "Show target collection": "显示目标收藏",
        "Shutter": "快门",
        "Size": "尺寸",
        "Skin": "皮肤",
        "Skin & Language": "皮肤与语言",
        "Skin: %@": "皮肤：%@",
        "Smaller for Mail (JPEG, 2048 px)": "缩小后发送（JPEG，2048 px）",
        "Smart": "智能相册",
        "Soft pink white": "柔和粉白",
        "Sort": "排序",
        "Sort order": "排序方式",
        "Star rating · clear": "评星 · 清除",
        "Stop Analyzing": "停止分析",
        "Stop analyzing": "停止分析",
        "Suggested examples: Reject, Maybe, Selected, Published, Personal": "示例：淘汰、待定、精选、已发布、私人",
        "Target Collection ✓": "目标收藏 ✓",
        "Target collection — B adds to it": "目标收藏 — 按 B 添加",
        "Target collection: “%@” (B)": "目标收藏：“%@” (B)",
        "This list": "本列表",
        "This only changes filenames on disk. Pixels and EXIF stay the same.": "只修改磁盘上的文件名，像素和 EXIF 保持不变。",
        "Thumbnail size (⌘= / ⌘−)": "缩略图大小 (⌘= / ⌘−)",
        "Toggle All Panels  ⇧Tab": "切换全部面板  ⇧Tab",
        "Toggle All Panels (⇧Tab)": "切换全部面板 (⇧Tab)",
        "Toggle Fit / 1:1": "切换 适合窗口 / 1:1",
        "Toggle Fit / 1:1 (Z, Space, or double-click)": "切换 适合窗口 / 1:1（Z、空格或双击）",
        "Toggle Flag (`)": "切换旗标 (`)",
        "Toggle Side Panels  Tab": "切换侧边面板  Tab",
        "Toggle Side Panels (Tab)": "切换侧边面板 (Tab)",
        "Toggle Zoom (Z)": "切换缩放 (Z)",
        "Toggle all panels": "切换全部面板",
        "Toggle pick flag": "切换留用旗标",
        "Toggle side panels": "切换侧边面板",
        "Tokens: {name} {n} {nnn} {date} {camera}": "占位符：{name} {n} {nnn} {date} {camera}",
        "Top Bar": "顶栏",
        "Top Bar  F5": "顶栏  F5",
        "Top Bar (F5)": "顶栏 (F5)",
        "Top bar": "顶栏",
        "Try clearing filters or choosing another Smart album.": "试试清除筛选，或选择其他智能相册。",
        "Type a place, e.g. “上海 外滩” or “Yosemite”. It becomes searchable and appears under Places. The photo files are not changed.": "输入地点，例如“上海 外滩”或“Yosemite”。之后可被搜索并出现在“地点”中，照片文件不会改变。",
        "Undo": "撤销",
        "Undo / redo marks": "撤销 / 重做标记",
        "Undo Mark (⌘Z)": "撤销标记 (⌘Z)",
        "Unflag  U": "取消旗标  U",
        "Unflag (U)": "取消旗标 (U)",
        "Unflagged": "无旗标",
        "Unit": "单位",
        "Unknown camera": "未知相机",
        "Unknown lens": "未知镜头",
        "Uses export settings: ": "使用导出设置：",
        "View": "视图",
        "Views & Panels": "视图与面板",
        "Warm paper white": "暖白纸感",
        "Web, social media, most screens": "网页、社交媒体、大多数屏幕",
        "Wide gamut for Apple devices and modern displays": "广色域，适合 Apple 设备和新款显示器",
        "Wide gamut for print workflows": "广色域，适合印刷流程",
        "Yellow": "黄色",
        "Zoom": "缩放",
        "Zoom In": "放大",
        "Zoom Out": "缩小",
        "Zoom at cursor": "以光标为中心缩放",
        "Zoom in (⌘= or scroll wheel)": "放大（⌘= 或滚轮）",
        "Zoom in / out (grid: thumbnail size)": "放大 / 缩小（网格中调整缩略图大小）",
        "Zoom out (⌘−)": "缩小 (⌘−)",
        "edited": "已手动修改",
        "original size": "原始尺寸",
        "“%@” is empty": "“%@”是空的",
        "≈ %@ for %@ files": "约 %@（%@ 个文件）",
        "⌘-click to combine groups": "⌘-点按可组合多个分组",
        "⌘-click to combine places": "⌘-点按可组合多个地点",
        "⌘N to create, or press B to add to a Quick Collection. Drag photos onto a collection.": "按 ⌘N 新建，或按 B 加入快速收藏；也可以把照片拖到收藏上。",
        "⌥⌘K next  ·  ⇧⌥⌘K previous": "⌥⌘K 下一个  ·  ⇧⌥⌘K 上一个",
    ]
}
